# Generated by Django 3.1 on 2020-09-09 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flightNo', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('airline', models.CharField(max_length=100)),
                ('seatsAvailable', models.IntegerField()),
                ('departureLocation', models.CharField(max_length=100)),
                ('arrivalLocation', models.CharField(max_length=100)),
                ('flightDateTime', models.DateTimeField()),
                ('flightDuration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('departureTerminal', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('planeID', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('planeType', models.CharField(max_length=10)),
                ('seatsAvailable', models.IntegerField()),
                ('seatsPerRow', models.IntegerField()),
                ('seatCollumns', models.IntegerField()),
                ('seatsEconomyClass', models.IntegerField()),
                ('seatsBusinessClass', models.IntegerField()),
                ('seatsFirstClass', models.IntegerField()),
                ('economyCost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('businessCost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('firstCost', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingRef', models.CharField(max_length=6)),
                ('seatNo', models.CharField(max_length=3)),
                ('passenger_passportNo', models.CharField(max_length=13)),
                ('passengerNames', models.CharField(max_length=100)),
                ('passengerSurname', models.CharField(max_length=100)),
                ('ticket_Cancelled', models.BooleanField(default=False)),
                ('booked_MemberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('flightNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.flights')),
            ],
        ),
        migrations.AddField(
            model_name='flights',
            name='planeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.planes'),
        ),
    ]
