# Generated by Django 3.1 on 2020-09-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flights',
            new_name='Flight',
        ),
        migrations.RenameModel(
            old_name='Planes',
            new_name='Plane',
        ),
    ]
