# Generated by Django 3.1 on 2020-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_history',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
