# Generated by Django 3.1 on 2020-09-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_ticket_history_payed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_history',
            old_name='payed',
            new_name='paid',
        ),
    ]
