# Generated by Django 3.1 on 2020-09-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_plane_seatcollumns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='businessCost',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='economyCost',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='firstCost',
        ),
        migrations.AddField(
            model_name='flight',
            name='businessCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='flight',
            name='economyCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='flight',
            name='firstCost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
