# Generated by Django 3.1 on 2020-09-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20200909_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_history',
            name='seatClass',
            field=models.CharField(choices=[('e', 'Economy Class'), ('b', 'Business Class'), ('f', 'FIRST CLASS')], default='e', max_length=1),
        ),
    ]
