# Generated by Django 3.1 on 2020-09-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_ticket_history_seatclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_history',
            name='seatClass',
            field=models.CharField(choices=[('e', 'Economy Class'), ('b', 'Business Class'), ('f', 'First Class')], default='e', max_length=1),
        ),
    ]
