# Generated by Django 3.1 on 2020-09-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20200910_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_history',
            name='passengerNames',
            field=models.CharField(max_length=100, verbose_name='Passanger Name'),
        ),
        migrations.AlterField(
            model_name='ticket_history',
            name='passengerSurname',
            field=models.CharField(max_length=100, verbose_name='Passanger Surname'),
        ),
        migrations.AlterField(
            model_name='ticket_history',
            name='passenger_passportNo',
            field=models.CharField(max_length=13, verbose_name='Passanger ID/Passport Number'),
        ),
    ]
