# Generated by Django 3.1 on 2020-09-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20200911_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flightDuration',
            field=models.TimeField(),
        ),
    ]
